### ISSUE TITLE
Other options for filtering reads

### ISSUE THREAD

**Issue by thm52126** [edgardomortiz/Captus#17]
Hi, this is a great pipeline, and I am finding it useful for multiple datasets. I have two questions regarding the cleaning step:
1. Is there an option to remove PCR duplicate reads from my FASTQ files? I had one sequencing run that looks like consisted of over-amplified libraries, and I feel like this could be inflating the number of paralogs during the extraction step. I may be wrong if there is an artefact in my resulting extractions/ paralog inference but just a thought.
2. Is there any additional option that could be set to filter out contaminant sequences from custom-set databases? I am looking some of my mitochondrial gene assemblies and am noticing that blast to a handful of fungi accessions on GenBank. One way around this could be just raising "--nuc_min_identity" to something like 75 or 80.
Thank you for your time!

**Comment by edgardomortiz** [comment]
Hi @thm52126 

Thanks for the comments, like you say, when the depth is to high some extra paralogs start to show up, we are working to filter irrelevant paralogs (or at least rank them last) for our next version. The idea of removing PCR duplicates during cleaning is good, I will explore the current options to implement this quickly.


Edgardo

**Comment by thm52126** [comment]
Thanks for your response and for your work developing this tool!
